# wrangler.toml

# The name of your project, taken from the warning message.
name = "pmw"

# The compatibility date, taken from the error message.
compatibility_date = "2025-07-18"

# This tells wrangler to deploy your site as static assets from the "dist" folder.
# This is the most important part for a static site.
[site]
bucket = "./dist"